### ISSUE TITLE
ぽんぺでエラーが出る

### ISSUE THREAD

**Issue by hideo54** [tsg-ut/slackbot#299]
たまたまログ読んでたら見つけたんですが、
```
TypeError: Cannot read property 'startsWith' of undefined
    at /home/slackbot/slackbot/ponpe/index.ts:130:54
    at Generator.next (<anonymous>)
    at /home/slackbot/slackbot/ponpe/index.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/slackbot/slackbot/ponpe/index.ts:4:12)
    at RTMClient.<anonymous> (/home/slackbot/slackbot/ponpe/index.ts:88:38)
    at RTMClient.emit (/home/slackbot/slackbot/node_modules/eventemitter3/index.js:202:33)
    at RTMClient.onWebsocketMessage (/home/slackbot/slackbot/node_modules/@slack/rtm-api/src/RTMClient.ts:626:10)
    at WebSocket.onMessage (/home/slackbot/slackbot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:203:13
    at WebSocket.EventEmitter.emit (domain.js:471:20
    at Receiver.receiverOnMessage (/home/slackbot/slackbot/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:203:13)
    at Receiver.EventEmitter.emit (domain.js:471:20)
    at Receiver.dataMessage (/home/slackbot/slackbot/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/home/slackbot/slackbot/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/home/slackbot/slackbot/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/slackbot/slackbot/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at Receiver.Writable.write (_stream_writable.js:301:11)
    at TLSSocket.socketOnData (/home/slackbot/slackbot/node_modules/ws/lib/websocket.js:795:35)
    at TLSSocket.emit (events.js:203:13)
    at TLSSocket.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:210:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17)
```
というエラーが出ていました。

とりあえず、ぽんぺの生みの親の @satos---jp に assign しておきます。

**Comment by cookie-s** [comment]
あれ、 https://github.com/tsg-ut/slackbot/pull/398 でfixされたのかしら
