### ISSUE TITLE
room gachaのテストが落ちてる

### ISSUE THREAD

**Issue by Yosshi999** [tsg-ut/slackbot#385]
```FAIL room-gacha/index.test.ts
  room-gacha
    ✕ responds to "物件ガチャ" with a prefecture and a city specified (3 ms)

  ● room-gacha › responds to "物件ガチャ" with a prefecture and a city specified

    TypeError: Cannot read property 'options' of undefined

      10 |         tinyreq.impl = jest.fn(async (url, callback) => {
      11 |             const data = await fs.readFile(`${__dirname}/city-select.test.html`, 'utf-8');
    > 12 |             if (callback) callback(null, data);
         |                           ^
      13 |             return data;
      14 |         });
      15 |         const osakaData = await fetchData('osaka');

      at Function.exports.load (node_modules/cheerio-req/node_modules/cheerio/lib/static.js:17:57)
      at node_modules/cheerio-req/lib/index.js:24:26
      at room-gacha/_dataGenerator.test.ts:12:27
      at fulfilled (room-gacha/_dataGenerator.test.ts:5:58)
```

**Comment by hideo54** [comment]
エーン

**Comment by hideo54** [comment]
ここから壊れ始めたぽいな 658755d7fff6aeafa7e2aee4ea3078d248a1b11b

(テスト落ちてる状態放置しているとこういう時 commit 探るのに時間がかかるのでつらい…)

**Comment by hideo54** [comment]
これうちの手元じゃ再現しない (テスト通る) んだよなぁ… :cry:

**Comment by hideo54** [comment]
うーーーん Actions のやってること完コピしたけど普通に通って泣いてしまった

ちなみにくっきーさんも再現できないらしいです (証人++;)

**Comment by hideo54** [comment]
ちなみにこれも謎
```
FAIL room-gacha/_dataGenerator.test.ts
  room-gacha _dataGenerator
    ✕ generates correct data (2 ms)

  ● room-gacha _dataGenerator › generates correct data

    ENOENT: no such file or directory, open '/home/runner/work/slackbot/slackbot/lib/bep-ss-2.3/bep-eng.dic'
```

**Comment by hideo54** [comment]
そもそもエラー出力の言ってることなんかおかしくね (`index.test.ts` で書いてるテストのエラーが `_dataGenerator.test.ts` で書いてるテストの内容になっている、明らかに関係ない辞書ファイルが見つからないと怒られている、など) というのもあって、GitHub Actions 側の問題と見て調査を進めます。

**Comment by hideo54** [comment]
怪しかった `_dataGenerator.test.ts` 消すと通るな。テストで `fs.readFile` してるのが地雷な気がせえへん?

**Comment by hideo54** [comment]
readFile せずに直接文字列貼り付けたら通るので、原因はこいつで確定かな…
```
(node:4042) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/runner/work/slackbot/slackbot/lib/bep-ss-2.3/bep-eng.dic'
```
は相変わらず出るけど、これでは落ちない (別件っぽい)

さて、現実的な対処法としてはこのテストを消すというのでいいと思う。PR 出します。

**Comment by hideo54** [comment]
てなわけで解決させました。 #388
