### ISSUE TITLE
pwnyaaのエラーぽよ

### ISSUE THREAD

**Issue by smallkirby** [tsg-ut/slackbot#556]
```{
  "level": "error",
  "message": "TypeError: Cannot read properties of null (reading 'solvedChalls')\n at /home/slackbot/slackbot/pwnyaa/index.ts:822:17\n at Generator.next (<anonymous>)\n at fulfilled (/home/slackbot/slackbot/pwnyaa/index.ts:5:58)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "timestamp": "2021-11-16T11:34:58.434Z"
}```

**Comment by smallkirby** [comment]
これはぼくがtwitterのIDを変えたことに起因しています :kusa:
