### ISSUE TITLE
sunriseのテストがおちてる

### ISSUE THREAD

**Issue by cookie-s** [tsg-ut/slackbot#578]
なんで

```
FAIL sunrise/index.test.js (10.702 s)
  sunrise
    ✕ notify sunrise on sunrise (5011 ms)
    ✕ notify sunset on sunset (5004 ms)

  ● sunrise › notify sunrise on sunrise

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      27 | 	});
      28 |
    > 29 | 	it('notify sunrise on sunrise', () => new Promise((resolve) => {
         | 	^
      30 | 		clock.setSystemTime(new Date('2019-03-21T06:00:00+0900'));
      31 |
      32 | 		slack.on('chat.postMessage', ({text}) => {

      at sunrise/index.test.js:29:2
      at Object.<anonymous> (sunrise/index.test.js:15:1)

  ● sunrise › notify sunset on sunset

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      39 | 	}));
      40 |
    > 41 | 	it('notify sunset on sunset', () => new Promise((resolve) => {
         | 	^
      42 | 		clock.setSystemTime(new Date('2019-03-21T19:00:00+0900'));
      43 |
      44 | 		slack.on('chat.postMessage', ({text}) => {

      at sunrise/index.test.js:41:2
      at Object.<anonymous> (sunrise/index.test.js:15:1)
```

**Comment by cookie-s** [comment]
https://github.com/tsg-ut/slackbot/commit/e2eb2a2cc397076b946fab86ab26c33af3eb8a4b

**Comment by cookie-s** [comment]
なんでsetIntervalをコメントアウトしたんだろう
